/// Daily reading model for personalized palm + astrology readings
class DailyReading {
  final bool success;
  final bool hasPalmProfile;
  final String date;
  final Astronomy astronomy;
  final ReadingContent reading;
  final String userName;

  DailyReading({
    required this.success,
    required this.hasPalmProfile,
    required this.date,
    required this.astronomy,
    required this.reading,
    required this.userName,
  });

  factory DailyReading.fromJson(Map<String, dynamic> json) {
    return DailyReading(
      success: json['success'] ?? false,
      hasPalmProfile: json['hasPalmProfile'] ?? false,
      date: json['date'] ?? '',
      astronomy: Astronomy.fromJson(json['astronomy'] ?? {}),
      reading: ReadingContent.fromJson(json['reading'] ?? {}),
      userName: json['userName'] ?? '',
    );
  }
}

/// Astronomy data for the day
class Astronomy {
  final MoonPhase moonPhase;
  final MoonSign moonSign;
  final ActiveLine activeLine;

  Astronomy({
    required this.moonPhase,
    required this.moonSign,
    required this.activeLine,
  });

  factory Astronomy.fromJson(Map<String, dynamic> json) {
    return Astronomy(
      moonPhase: MoonPhase.fromJson(json['moonPhase'] ?? {}),
      moonSign: MoonSign.fromJson(json['moonSign'] ?? {}),
      activeLine: ActiveLine.fromJson(json['activeLine'] ?? {}),
    );
  }
}

class MoonPhase {
  final String phase;
  final String phaseTr;
  final String phaseEn;
  final String icon;

  MoonPhase({
    required this.phase,
    required this.phaseTr,
    required this.phaseEn,
    required this.icon,
  });

  factory MoonPhase.fromJson(Map<String, dynamic> json) {
    return MoonPhase(
      phase: json['phase'] ?? '',
      phaseTr: json['phaseTr'] ?? '',
      phaseEn: json['phaseEn'] ?? '',
      icon: json['icon'] ?? '🌙',
    );
  }

  /// Get phase name based on language
  String getName(bool isTurkish) => isTurkish ? phaseTr : phaseEn;
}

class MoonSign {
  final String sign;
  final String signTr;
  final String signEn;
  final String icon;
  final String element;
  final String elementTr;
  final String elementEn;

  MoonSign({
    required this.sign,
    required this.signTr,
    required this.signEn,
    required this.icon,
    required this.element,
    required this.elementTr,
    required this.elementEn,
  });

  factory MoonSign.fromJson(Map<String, dynamic> json) {
    return MoonSign(
      sign: json['sign'] ?? '',
      signTr: json['signTr'] ?? '',
      signEn: json['signEn'] ?? '',
      icon: json['icon'] ?? '♈',
      element: json['element'] ?? '',
      elementTr: json['elementTr'] ?? '',
      elementEn: json['elementEn'] ?? '',
    );
  }

  /// Get sign name based on language
  String getName(bool isTurkish) => isTurkish ? signTr : signEn;

  /// Get element name based on language
  String getElement(bool isTurkish) => isTurkish ? elementTr : elementEn;
}

class ActiveLine {
  final String line;
  final String lineTr;
  final String lineEn;
  final String planet;
  final String planetTr;
  final String planetEn;

  ActiveLine({
    required this.line,
    required this.lineTr,
    required this.lineEn,
    required this.planet,
    required this.planetTr,
    required this.planetEn,
  });

  factory ActiveLine.fromJson(Map<String, dynamic> json) {
    return ActiveLine(
      line: json['line'] ?? '',
      lineTr: json['lineTr'] ?? '',
      lineEn: json['lineEn'] ?? '',
      planet: json['planet'] ?? '',
      planetTr: json['planetTr'] ?? '',
      planetEn: json['planetEn'] ?? '',
    );
  }

  /// Get line name based on language
  String getName(bool isTurkish) => isTurkish ? lineTr : lineEn;

  /// Get planet name based on language
  String getPlanet(bool isTurkish) => isTurkish ? planetTr : planetEn;
}

/// Reading content generated by AI
class ReadingContent {
  final String greeting;
  final String dailyEnergy;
  final String activeLineReading;
  final String moonInfluence;
  final String advice;
  final LuckyElements luckyElements;
  final String? warning;

  ReadingContent({
    required this.greeting,
    required this.dailyEnergy,
    required this.activeLineReading,
    required this.moonInfluence,
    required this.advice,
    required this.luckyElements,
    this.warning,
  });

  factory ReadingContent.fromJson(Map<String, dynamic> json) {
    return ReadingContent(
      greeting: json['greeting'] ?? '',
      dailyEnergy: json['dailyEnergy'] ?? '',
      activeLineReading: json['activeLineReading'] ?? '',
      moonInfluence: json['moonInfluence'] ?? '',
      advice: json['advice'] ?? '',
      luckyElements: LuckyElements.fromJson(json['luckyElements'] ?? {}),
      warning: json['warning'],
    );
  }
}

class LuckyElements {
  final String color;
  final String colorDescription;
  final String number;
  final String numberDescription;
  final String time;
  final String timeDescription;

  LuckyElements({
    required this.color,
    required this.colorDescription,
    required this.number,
    required this.numberDescription,
    required this.time,
    required this.timeDescription,
  });

  factory LuckyElements.fromJson(Map<String, dynamic> json) {
    return LuckyElements(
      color: json['color'] ?? '',
      colorDescription: json['colorDescription'] ?? '',
      number: json['number']?.toString() ?? '',
      numberDescription: json['numberDescription'] ?? '',
      time: json['time'] ?? '',
      timeDescription: json['timeDescription'] ?? '',
    );
  }
}
